# Generated by Django 5.1.2 on 2024-12-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
